services:
  lot-db:
    image: postgres:latest
    container_name: lot-db
    environment:
      POSTGRES_DB: lot
      POSTGRES_USER: lot
      POSTGRES_PASSWORD: lot
    ports:
      - "5432:5432"
    volumes:
      - lot-db-data:/var/lib/postgresql/data

#  lotservice.api:
#    image: lotservice.api
#    depends_on:
#      - lot-db
#    restart: on-failure
#    healthcheck:
#      test: [ “CMD”, “curl”, “-f”, “http://localhost:8080” ]
#      interval: 30s
#      timeout: 10s
#      retries: 3      
#    environment:
#      ConnectionString: "Host=lot-db;Port=5432;Database=lot;User Id=lot;Password=lot"
#    build:
#      context: .
#      dockerfile: LotService.Api/Dockerfile
      
volumes:
  lot-db-data: